# Generated by Django 4.0.4 on 2022-08-31 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Segundo_Trimestre', '0003_alter_habilitacao_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Segundo_Trimestre.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=13)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segundo_Trimestre.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segundo_Trimestre.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='CorretorAtendeRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segundo_Trimestre.corretor')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segundo_Trimestre.regiao')),
            ],
        ),
    ]
