# Generated by Django 4.0.4 on 2022-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Segundo_Trimestre', '0004_corretor_municipio_telefone_regiao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='uf',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
