# Generated by Django 4.0.4 on 2022-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Segundo_Trimestre', '0005_alter_municipio_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='uf',
            field=models.CharField(max_length=2),
        ),
    ]
